# This is a basic workflow that is manually triggered

name: Manual workflow

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install

  test-with-babel-jest:
    name: Run tests with babel-jest
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: prepare

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: yarn test --ci --config jest.config.js

  test-with-ts-jest:
    name: Run tests with ts-jest.
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: yarn test --ci --config ts-jest.config.js
